sudo: false
language: node_js

node_js:
  - "7"

cache:
  yarn: false
  directories:
    - "node_modules"

script:
  - npm test:lint
  - npm t

notifications:
  slack: heteiland:g4vLefTvS5BFrGwjXHzaquwM
